export default [
	{
		ignores: ['_worker.js', 'dist/**', '.wrangler/**', 'node_modules/**', 'scratch/**'],
	},
	{
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			globals: {
				// Cloudflare Workers & Standard Web globals
				fetch: 'readonly',
				Request: 'readonly',
				Response: 'readonly',
				Headers: 'readonly',
				URL: 'readonly',
				URLSearchParams: 'readonly',
				WebSocket: 'readonly',
				WebSocketPair: 'readonly',
				crypto: 'readonly',
				TextEncoder: 'readonly',
				TextDecoder: 'readonly',
				atob: 'readonly',
				btoa: 'readonly',
				console: 'readonly',
				ReadableStream: 'readonly',
				WritableStream: 'readonly',
				TransformStream: 'readonly',
				IdentityTransformStream: 'readonly',
				ByteLengthQueuingStrategy: 'readonly',
				CountQueuingStrategy: 'readonly',
				CompressionStream: 'readonly',
				DecompressionStream: 'readonly',
				Uint8Array: 'readonly',
				Uint16Array: 'readonly',
				Uint32Array: 'readonly',
				Int8Array: 'readonly',
				Int16Array: 'readonly',
				Int32Array: 'readonly',
				BigUint64Array: 'readonly',
				BigInt64Array: 'readonly',
				Float32Array: 'readonly',
				Float64Array: 'readonly',
				ArrayBuffer: 'readonly',
				DataView: 'readonly',
				Set: 'readonly',
				Map: 'readonly',
				WeakSet: 'readonly',
				WeakMap: 'readonly',
				Promise: 'readonly',
				Blob: 'readonly',
				File: 'readonly',
				FormData: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				queueMicrotask: 'readonly',
				performance: 'readonly',
				process: 'readonly',
				Buffer: 'readonly',
				SubtleCrypto: 'readonly',
				CryptoKey: 'readonly',
				AbortController: 'readonly',
				AbortSignal: 'readonly',
				structuredClone: 'readonly',
				Event: 'readonly',
				EventTarget: 'readonly',
				MessageEvent: 'readonly',
				CloseEvent: 'readonly',
				ErrorEvent: 'readonly',
				caches: 'readonly',
				navigator: 'readonly',
				BigInt: 'readonly',
			},
		},
		rules: {
			'no-undef': 'error',
			'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
			'no-console': 'off',
			'prefer-const': 'warn',
		},
	},
];
