/**
 * src/utils/helpers.js
 * Auto-generated from _worker.js refactor
 * Original: edgetunnel 2.1 (2026-08-11)
 */

export function toUint8Array(data) {
	if (data instanceof Uint8Array) return data;
	if (data instanceof ArrayBuffer) return new Uint8Array(data);
	if (ArrayBuffer.isView(data))
		return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
	return new Uint8Array(data || 0);
}

export function concatByteData(...chunkList) {
	if (!chunkList || chunkList.length === 0) return new Uint8Array(0);
	const chunks = chunkList.map(toUint8Array);
	const total = chunks.reduce((sum, c) => sum + c.byteLength, 0);
	const result = new Uint8Array(total);
	let offset = 0;
	for (const c of chunks) {
		result.set(c, offset);
		offset += c.byteLength;
	}
	return result;
}

export function log(...args) {
	if (debugLogging) console.log(...args);
}

export function randomPath(fullNodePath = '/') {
	const commonPathDirs = [
		'about',
		'account',
		'acg',
		'act',
		'activity',
		'ad',
		'ads',
		'ajax',
		'album',
		'albums',
		'anime',
		'api',
		'app',
		'apps',
		'archive',
		'archives',
		'article',
		'articles',
		'ask',
		'auth',
		'avatar',
		'bbs',
		'bd',
		'blog',
		'blogs',
		'book',
		'books',
		'bt',
		'buy',
		'cart',
		'category',
		'categories',
		'cb',
		'channel',
		'channels',
		'chat',
		'china',
		'city',
		'class',
		'classify',
		'clip',
		'clips',
		'club',
		'cn',
		'code',
		'collect',
		'collection',
		'comic',
		'comics',
		'community',
		'company',
		'config',
		'contact',
		'content',
		'course',
		'courses',
		'cp',
		'data',
		'detail',
		'details',
		'dh',
		'directory',
		'discount',
		'discuss',
		'dl',
		'dload',
		'doc',
		'docs',
		'document',
		'documents',
		'doujin',
		'download',
		'downloads',
		'drama',
		'edu',
		'en',
		'ep',
		'episode',
		'episodes',
		'event',
		'events',
		'f',
		'faq',
		'favorite',
		'favourites',
		'favs',
		'feedback',
		'file',
		'files',
		'film',
		'films',
		'forum',
		'forums',
		'friend',
		'friends',
		'game',
		'games',
		'gif',
		'go',
		'go.html',
		'go.php',
		'group',
		'groups',
		'help',
		'home',
		'hot',
		'htm',
		'html',
		'image',
		'images',
		'img',
		'index',
		'info',
		'intro',
		'item',
		'items',
		'ja',
		'jp',
		'jump',
		'jump.html',
		'jump.php',
		'jumping',
		'knowledge',
		'lang',
		'lesson',
		'lessons',
		'lib',
		'library',
		'link',
		'links',
		'list',
		'live',
		'lives',
		'm',
		'mag',
		'magnet',
		'mall',
		'manhua',
		'map',
		'member',
		'members',
		'message',
		'messages',
		'mobile',
		'movie',
		'movies',
		'music',
		'my',
		'new',
		'news',
		'note',
		'novel',
		'novels',
		'online',
		'order',
		'out',
		'out.html',
		'out.php',
		'outbound',
		'p',
		'page',
		'pages',
		'pay',
		'payment',
		'pdf',
		'photo',
		'photos',
		'pic',
		'pics',
		'picture',
		'pictures',
		'play',
		'player',
		'playlist',
		'post',
		'posts',
		'product',
		'products',
		'program',
		'programs',
		'project',
		'qa',
		'question',
		'rank',
		'ranking',
		'read',
		'readme',
		'redirect',
		'redirect.html',
		'redirect.php',
		'reg',
		'register',
		'res',
		'resource',
		'retrieve',
		'sale',
		'search',
		'season',
		'seasons',
		'section',
		'seller',
		'series',
		'service',
		'services',
		'setting',
		'settings',
		'share',
		'shop',
		'show',
		'shows',
		'site',
		'soft',
		'sort',
		'source',
		'special',
		'star',
		'stars',
		'static',
		'stock',
		'store',
		'stream',
		'streaming',
		'streams',
		'student',
		'study',
		'tag',
		'tags',
		'task',
		'teacher',
		'team',
		'tech',
		'temp',
		'test',
		'thread',
		'tool',
		'tools',
		'topic',
		'topics',
		'torrent',
		'trade',
		'travel',
		'tv',
		'txt',
		'type',
		'u',
		'upload',
		'uploads',
		'url',
		'urls',
		'user',
		'users',
		'v',
		'version',
		'videos',
		'view',
		'vip',
		'vod',
		'watch',
		'web',
		'wenku',
		'wiki',
		'work',
		'www',
		'zh',
		'zh-cn',
		'zh-tw',
		'zip',
	];
	const randomCount = Math.floor(Math.random() * 3 + 1);
	const randomPath = commonPathDirs
		.sort(() => 0.5 - Math.random())
		.slice(0, randomCount)
		.join('/');
	if (fullNodePath === '/') return `/${randomPath}`;
	else return `/${randomPath + fullNodePath.replace('/?', '?')}`;
}

export function replaceWildcardWithRandomChars(content) {
	if (typeof content !== 'string' || !content.includes('*')) return content;
	const charset = 'abcdefghijklmnopqrstuvwxyz0123456789';
	return content.replace(/\*/g, () => {
		let s = '';
		for (let i = 0; i < Math.floor(Math.random() * 14) + 3; i++)
			s += charset[Math.floor(Math.random() * charset.length)];
		return s;
	});
}

export async function parseToArray(content) {
	var cleanedContent = content.replace(/[	"'\r\n]+/g, ',').replace(/,+/g, ',');
	if (cleanedContent.charAt(0) == ',') cleanedContent = cleanedContent.slice(1);
	if (cleanedContent.charAt(cleanedContent.length - 1) == ',')
		cleanedContent = cleanedContent.slice(0, cleanedContent.length - 1);
	const addressArray = cleanedContent.split(',');
	return addressArray;
}
